void	main(void);
void	putbuf(void);
void	cancel(void);
Point	drawchar(Point p, int *c);
void	search(void);
void	scrollup(void);
void	scrolldown(void);
void	logcmd(Keyfn *fn);
void	redraw(void);
void	quit(void);
void	unused(void);
Keyfn*	fnlookup(Rune r);
void	guisetup(void);
void	alignbigpoint(void);
void	fillrect(Rectangle r, Image *i, int f);
void	mkgfx(void);
void	newline(void);
void	badsearch(void);
Point	linetop(int n);
void	drawfrom(Point p);
void	backspace(void);
void	drawstr(Point p, char *s, int bw);
void	eresized(int);
